development:
    bucket: www.antho.co
    access_key_id: AKIAIKNSA6IYZ72PXGOQ
    secret_access_key: 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

test:
    bucket: www.antho.co
    access_key_id: AKIAIKNSA6IYZ72PXGOQ
    secret_access_key: 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

production:
    bucket: www.antho.co
    access_key_id: AKIAIKNSA6IYZ72PXGOQ
    secret_access_key: 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